# Generated by Django 5.2.17 on 2026-10-02 16:13

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="events.careerfield",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="America/Denver", max_length=64)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In person"),
                            ("HYBRID", "Hybrid"),
                            ("LIVE_VIRTUAL", "Live virtual"),
                            ("WEBINAR", "Webinar"),
                            ("ASYNCHRONOUS", "Asynchronous"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("organizer_name", models.CharField(blank=True, max_length=200)),
                ("organizer_url", models.URLField(blank=True)),
                ("venue_name", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_region", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("topic_tags", models.JSONField(blank=True, default=list)),
                ("likely_attendee_types", models.JSONField(blank=True, default=list)),
                ("experience_levels", models.JSONField(blank=True, default=list)),
                ("networking_relevant", models.BooleanField(default=False)),
                (
                    "networking_strength",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "career_fields",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="events.careerfield"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventSourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=255)),
                ("source_url", models.URLField(max_length=500)),
                ("raw_data", models.JSONField(default=dict)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_records",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["format", "start_time"], name="events_even_format_bb6192_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["networking_relevant", "start_time"], name="events_even_network_a7a84d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventsourcerecord",
            index=models.Index(
                fields=["provider", "external_id"], name="events_even_provide_3d60e1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsourcerecord",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_id"), name="unique_provider_external_event"
            ),
        ),
    ]
